baseURL: https://gcau.mikehughes.info/
languageCode: en-us
title: GopherConAU
theme: hugo-fresh
googleAnalytics: UA-123456789-1

publishDir: docs
params:
  navbarlogo:
  # Logo (from /images/logos/___)
   # image: logos/fresh.svg
   # link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: GopherconAU 2019
    # Hero subtitle (optional)
    subtitle: First ever Golang conference in Australia!
    # Button text
    # buttontext: Follow on LinkedIn For Updates!
    # Where the main hero button links to
    # buttonlink: "https://www.linkedin.com/company/gopherconau/"
    # Hero image (from /images/___)
    image: illustrations/logo-ashley.jpg
    # Footer logos (from /images/logos/clients/___.svg)
  #  clientlogos:
  #  - systek
  #  - tribe
  #  - kromo
  #  - infinite
  #  - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
    - title: About
      url: /#about
    - title: Contact
      url: /#contact
  # - title: Features
  #   url: /
  # - title: Pricing
  #   url: /
  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  # - title: Log in
  #   url: /
  # - title: Sign up
  #   url: /
  #   button: true
  # sidebar:
  #   # Logo (from /images/logos/___.svg)
  #   logo: fresh-square
  #   sections:
  #   - title: User
  #     icon: user
  #     links:
  #     - text: Profile
  #       url: /
  #     - text: Account
  #       url: /
  #     - text: Settings
  #       url: /
  #   - title: Messages
  #     icon: envelope
  #     links:
  #     - text: Inbox
  #       url: /
  #     - text: Compose
  #       url: /
  #   - title: Images
  #     icon: image
  #     links:
  #     - text: Library
  #       url: /
  #     - text: Upload
  #       url: /
  #   - title: Settings
  #     icon: cog
  #     links:
  #     - text: User settings
  #       url: /
  #     - text: App settings
  #       url: /

  # a custom section based on section 1 without tiles
  about:
    title: About
    subtitle: Why Should You Come to GopherConAU?
    paragraphs:
      - text: GopherConAU believes Go is the way to go! We wish to showcase this modern language here in beautiful Australia both as a successful tool for commercial programming and a viable career path. Part of our vision is to attract a diverse crowd both to the audience and to the stage. We aim the GopherCon Australia to reflect how we developers want the future of the industry to look.
      - text: For the first year of GopherCon Australia, we will use sponsorships to attract and accommodate for international speakers and workshop hosts. By showing that GopherCon Australia is a welcoming conference, we wish to create a sense of community coming from different backgrounds, supporting traditionally underrepresented groups in the technology industry. We invited prominent contributors to the Go tech scene, who share and represent our vision of inclusion and who come from diverse gender and ethnicity groups.
      - text: Many well known Australian companies use Go, including Google, Atlassian, VMware, Seek, Siteminder, Freelancer.com, Campaign Monitor, Sajari, and many more.
      - text: GopherCon Australia is the latest in a series of conferences originating from the first GopherCon held in Denver, Colorado in 2014. The conference founders are Katie Fry and Xuanyi Chew, both organisers of the successful Sydney Go Usersâ€™ Group, and a committee of volunteers.
      - text: GopherCon Australia is happening in Sydney between 30th October and 1st November 2019. Yes, you read it right - conveniently before the weekend, so that you can extend your stay. We encourage you to take your partner, family, or friends with you, as we will provide you with recommendations on how to spend time in Sydney to enjoy the culture, art, and fun.

  # a custom section based on section 4 because of the quirky background colour and section 1 to get the tiles design styled
  contact:
     title: Contact
     # subtitle: Who to Ask?
     contacts:
     - title: Twitter
       icon: logo-ashley.jpg
       text: Keeping you updated and entertained
       url: https://twitter.com/gopherconaunz
       buttonText: Read From @GopherConAUNZ
     - title: LinkedIn
       icon: gopher-kangaroo-plain-svg-small-margin.svg
       text: News in full seriousness of LinkedIn Business Page
       url: https://www.linkedin.com/company/gopherconau/
       buttonText: Visit GopherConAU Page
     - title: Mailling List
       icon: gopher-celebrating.svg
       text: To keep you in the loop with everything important
       url: /#mail
       buttonText: Join the Mailling List
  mailinglist:
    title: Mailing List
    # subtitle
    logo: gopher-kangaroo-sydney-opera.svg
    # subtitle: We will keep you in the loop

  # The entire schedule
  schedule:
    title: Schedule
    slots:
    - name: "Check-in / Breakfast"
      time: "9h00"

    - name: "Linus Torvalds"
      photo: "/images/speakers/default.png"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Linux Foundation"
      link:
        href: "http://twitter.com/linus"
        text: "@linus"
      presentation:
        title: "Digging into a Linux Kernel"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "10h00"

    - name: "Bill Gates"
      photo: "/images/speakers/default.png"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Microsoft"
      link:
        href: "http://github.com/billy95"
        text: "@billy95"
      presentation:
        title: "Introducing Windows 12"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "11h00"

    - name: "Lunch"
      time: "12h00"

    - name: "Chuck Norris"
      photo: "/images/speakers/default.png"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Delta Command"
      link:
        href: "http://twitter.com/littlechuck"
        text: "@littlechuck"
      presentation:
        title: "How to kill a elephant with one finger"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "13h00"

    - name: "Steve Jobs"
      photo: "/images/speakers/default.png"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Apple, Inc."
      link:
        href: "http://github.com/stevie"
        text: "@stevie"
      presentation:
        title: "Presenting iPad"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "14h00"

    - name: "Coffee-break"
      time: "15h00"

    - name: "Mark Zuckerberg"
      photo: "/images/speakers/default.png"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Facebook"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
      presentation:
        title: "Revealing Facebook Secrets"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "16h00"

    - name: "Steve Wozniak"
      photo: "/images/speakers/default.png"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Apple, Inc."
      link:
        href: "http://twitter.com/woz"
        text: "@woz"
      presentation:
        title: "Why do I prefer Android over iPhone"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "17h00"
        
  # section2:
  #   title: You're here because you want the best
  #   subtitle: And we know it
  #   features:
  #   - title: Powerful and unified interface
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     # Icon (from /images/illustrations/icons/___.svg)
  #     icon: laptop-globe
  #   - title: Cross-device synchronisation
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     icon: doc-sync
  #   - title: Nomad system
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     icon: mobile-feed
  # section3:
  #   title: One platform
  #   subtitle: To rule them all
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#"
  # section4:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  footer:
     # logo: gopher-kangaroo-sydney-opera.svg
     thanks:
       - text: The design of this website is an adaptation of Hugo Fresh by Stef Ma.
       - text: The Go gopher character was designed by Renee French under CC BY 3.0.
       - text: The GopherConAU logo was kindly created by Ashley McNamara.
       - text: The other gopher illustrations are based on creations of Egon Elbre.
     # Social media links (GitHub, Twitter, etc.). All are optional.
  #   socialmedia:
  #   - link: https://github.com/lucperkins/github-fresh
  #     # Icons are from Font Awesome
  #     icon: github
  #   - link: https://dribbble.com/#
  #     icon: dribbble
  #   - link: https://facebook.com/#
  #     icon: facebook
  #   - link: https://twitter.com/lucperkins
  #     icon: twitter
  #   - link: https://bitbucket.org/#
  #     icon: bitbucket
  #   bulmalogo: true
  #   quicklinks:
  #     column1:
  #       title: "Product"
  #       links:
  #       - text: Discover features
  #         link: /
  #       - text: Why choose our product?
  #         link: /
  #       - text: Compare features
  #         link: /
  #       - text: Our roadmap
  #         link: /
  #       - text: Request features
  #         link: /
  #     column2:
  #       title: "Docs"
  #       links:
  #       - text: Get started
  #         link: /
  #       - text: User guides
  #         link: /
  #       - text: Admin guide
  #         link: /
  #       - text: Developers
  #         link: /
  #     column3:
  #       title: "Blog"
  #       links:
  #       - text: Latest news
  #         link: /
  #       - text: Tech articles
  #         link: /
  #       - text: Video blog
  #         link: /
